-- AlterTable
ALTER TABLE `RoomType` ADD COLUMN `hasBathtub` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `hasTV` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `hasWifi` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `hasWindow` BOOLEAN NOT NULL DEFAULT true;
