// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/hotel": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/hotel" | "/dashboard" | "/login" | "/register" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "layouts/index.tsx": {
    id: "layouts/index";
    page: "/hotel" | "/dashboard";
  };
  "./views/hotel/index.tsx": {
    id: "views/hotel/index";
    page: "/hotel";
  };
  "./views/dashboard/index.tsx": {
    id: "views/dashboard/index";
    page: "/dashboard";
  };
  "layouts2/index.tsx": {
    id: "layouts2/index";
    page: "/" | "/login" | "/register";
  };
  "./views/welcome/welcome.tsx": {
    id: "views/welcome/welcome";
    page: "/";
  };
  "./views/login/index.tsx": {
    id: "views/login/index";
    page: "/login";
  };
  "./views/register/index.tsx": {
    id: "views/register/index";
    page: "/register";
  };
  "./views/NotFound.tsx": {
    id: "views/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "layouts/index": typeof import("./app/layouts/index.tsx");
  "views/hotel/index": typeof import("./app/./views/hotel/index.tsx");
  "views/dashboard/index": typeof import("./app/./views/dashboard/index.tsx");
  "layouts2/index": typeof import("./app/layouts2/index.tsx");
  "views/welcome/welcome": typeof import("./app/./views/welcome/welcome.tsx");
  "views/login/index": typeof import("./app/./views/login/index.tsx");
  "views/register/index": typeof import("./app/./views/register/index.tsx");
  "views/NotFound": typeof import("./app/./views/NotFound.tsx");
};